# Generated by Django 4.1.3 on 2023-04-01 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='create_data',
            new_name='create_date',
        ),
    ]
